### PR TITLE
Code refactoring

### PR DESCRIPTION
**Pull request by ryguigas0**
Comented at least 90% of the code, including the newest game over code

### CODE REVIEW

**Comment by ryguigas0** [comment]
Added the `checkGameOver()` function and comented the game over code

**Comment by sbdh11** [comment]
oof, this still shows the resolve conflicts

**Comment by ryguigas0** [comment]
oof, i'll try to fix it

**Comment by ryguigas0** [comment]
Fixed merge conflict #11, go take a look there!

**Pull request closed without merging**
